---
- hosts: jumpbox
  become: true
  tasks:
  - name: Add hosts in memory
    include_role:
       name: facts

  #Smoketest haproxy and tomcat
- hosts: frontends
  become: false
  tasks:
  - name: Smoketest haproxy and tomcat
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage

  - name: Fail if Ansible is not in the page content
    include_tasks: teardown.yml
    when: "'Ansible' not in webpage.content"

- hosts: appdbs
  become: false
  tasks:
  - name: Smoketest postgresql
    postgresql_db:
      name: testdb
    delegate_to: "{{ inventory_hostname }}"
    register: dbsmoke

  - name: fail if db smoke did not run correctly
    include_tasks: teardown.yml
    when: dbsmoke is not defined

  - name: Remove test database
    postgresql_db:
      name: testdb
      state: absent

 
